// ignore_for_file: constant_identifier_names

// const String MLAST_URAH = 'mLast_sorah';
const String FONT_SIZE = 'font_size';
const String LANG = "lang";
const String LANG_NAME = "langName";
const String LANGUAGE_FONT = "languageFont";
const String SET_THEME = "SET_THEME";
const String APP_FONT_FAMILY = 'APP_FONT_FAMILY';
const String SCREEN_SELECTED_VALUE = "SCREEN_SELECTED_VALUE";
final String SETTED_DATE_FOR_ZEKER = 'SETTED_DATE_FOR_ZEKER';
final String ZEKER_OF_THE_DAY_AND_ID = 'ZEKER_OF_THE_DAY_AND_ID';
final String LAST_SHOWN_UPDATE_INDEX = 'LAST_SHOWN_UPDATE_INDEX';
final String SETTED_DATE_FOR_AYAH = 'SETTED_DATE_FOR_AYAH';
final String AYAH_OF_THE_DAY_AND_AYAH_NUMBER = 'AYAH_OF_THE_DAY_AND_NUMBER';
final String TAFSIR_OF_THE_DAY_AND_TAFSIR_NUMBER =
    'TAFSIR_OF_THE_DAY_AND_NUMBER';
final String TAFSIR_OF_THE_DAY_RADIO_VALUE = 'TAFSIR_OF_THE_DAY_RADIO_VALUE';
final String DOWNLOADED_BOOKS = 'downloaded_books';
final String IS_TASHKIL = 'IS_TASHKIL';
final String BACKGROUND_PICKER_COLOR = 'BACKGROUND_PICKER_COLOR';
final String SEARCH_HISTORY = 'SEARCH_HISTORY';
final String AUDIO_SERVICE_INITIALIZED = 'AUDIO_SERVICE_INITIALIZED';
final String BACKGROUND_PICKER_COLOR_FOR_BOOK =
    'BACKGROUND_PICKER_COLOR_FOR_BOOK';
