import 'dart:async';
import 'dart:convert';
import 'dart:developer' show log;
import 'dart:io' show File;

import 'package:adhan/adhan.dart';
import 'package:alquranalkareem/core/services/location/location_enum.dart';
import 'package:arc_progress_bar_new/arc_progress_bar_new.dart';
import 'package:archive/archive.dart' show ZipDecoder;
import 'package:audio_service/audio_service.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_rounded_progress_bar/flutter_rounded_progress_bar.dart';
import 'package:flutter_rounded_progress_bar/rounded_progress_bar_style.dart';
import 'package:flutter_svg/svg.dart';
import 'package:gap/gap.dart';
import 'package:geocoding/geocoding.dart' as geo;
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:hijri/hijri_calendar.dart';
import 'package:intl/intl.dart' as intl;
import 'package:just_audio/just_audio.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:rive/rive.dart';
import 'package:slide_countdown/slide_countdown.dart';
import 'package:solar_icons/solar_icons.dart';
import 'package:square_percent_indicater/square_percent_indicater.dart';

import '/core/utils/constants/extensions/convert_number_extension.dart';
import '/core/utils/constants/extensions/extensions.dart';
import '/core/utils/constants/extensions/svg_extensions.dart';
import '../../../../../core/services/services_locator.dart';
import '../../../core/services/location/locations.dart';
import '../../../core/services/notifications_helper.dart';
import '../../../core/utils/constants/lists.dart';
import '../../../core/utils/constants/lottie.dart';
import '../../../core/utils/constants/lottie_constants.dart';
import '../../../core/utils/constants/shared_preferences_constants.dart';
import '../../../core/utils/constants/svg_constants.dart';
import '../../../core/utils/helpers/date_formatter.dart';
import '../../../core/widgets/occasions/controller/event_controller.dart';
import '../../controllers/general/general_controller.dart';
import '../quran_page/controllers/audio/audio_controller.dart';
import 'data/model/adhan_data.dart';
import 'data/model/prayer_day_model.dart';
import 'data/model/prayer_details.dart';

part 'controller/adhan/adhan_controller.dart';
part 'controller/adhan/adhan_state.dart';
part 'controller/adhan/extensions/adhan_getters.dart';
part 'controller/adhan/extensions/adhan_ui.dart';
part 'controller/adhan/extensions/location_extension.dart';
part 'controller/prayer_progress_controller.dart';
part 'controller/prayers_notifications/extensions/prayers_noti_ui.dart';
part 'controller/prayers_notifications/extensions/schedule_daily_extension.dart';
part 'controller/prayers_notifications/noti_state.dart';
part 'controller/prayers_notifications/prayers_notifications_controller.dart';
part 'data/model/prayer_list.dart';
part 'helpers/adhan_audio_downloader.dart';
part 'hijri_prayer_widget/hijri_widget.dart';
part 'hijri_prayer_widget/prayer_progress_bar_widget.dart';
part 'hijri_prayer_widget/prayer_widget.dart';
part 'hijri_prayer_widget/vertical_progress_bar.dart';
part 'prayer_build.dart';
part 'prayer_widget.dart';
part 'screen/occasions.dart';
part 'widgets/arabic_slide_countdown.dart';
part 'widgets/prayer_details.dart';
part 'widgets/prohibition_details.dart';
part 'widgets/settings/adhan_sounds.dart';
part 'widgets/settings/detect_location.dart';
part 'widgets/settings/pick_calculation_method.dart';
part 'widgets/settings/play_button.dart';
part 'widgets/settings/prayer_settings.dart';
part 'widgets/settings/set_timing_calculations.dart';
part 'widgets/settings/setting_prayer_times.dart';
part 'widgets/slide_countdown_widget.dart';
