import 'dart:async' show Completer;
import 'dart:convert' show json;
import 'dart:developer' show log;
import 'dart:io' show File, Directory;

import 'package:alquranalkareem/core/utils/helpers/app_text_styles.dart';
import 'package:alquranalkareem/core/widgets/expansion_tile_widget.dart';
import 'package:alquranalkareem/core/widgets/title_widget.dart';
import 'package:animated_custom_dropdown/custom_dropdown.dart';
import 'package:animated_search_bar/animated_search_bar.dart';
import 'package:another_xlider/another_xlider.dart';
import 'package:another_xlider/models/handler.dart';
import 'package:another_xlider/models/handler_animation.dart';
import 'package:another_xlider/models/trackbar.dart';
import 'package:drift/drift.dart' as drift;
import 'package:flex_color_picker/flex_color_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_rounded_progress_bar/flutter_rounded_progress_bar.dart';
import 'package:flutter_rounded_progress_bar/rounded_progress_bar_style.dart';
import 'package:flutter_scale_kit/flutter_scale_kit.dart';
import 'package:gap/gap.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:path_provider/path_provider.dart';
import 'package:quran_library/quran_library.dart' as quran_library;
import 'package:quran_library/src/service/internet_connection_controller.dart';

import '../../../core/widgets/app_bar_widget.dart';
import '/core/utils/constants/extensions/convert_number_extension.dart';
import '/core/utils/constants/extensions/extensions.dart';
import '/core/utils/constants/extensions/svg_extensions.dart';
import '/core/utils/constants/extensions/text_span_extension.dart';
import '../../../core/services/api_client.dart';
import '../../../core/utils/constants/extensions/bottom_sheet_extension.dart';
import '../../../core/utils/constants/extensions/custom_error_snackBar.dart';
import '../../../core/utils/constants/lottie.dart';
import '../../../core/utils/constants/lottie_constants.dart';
import '../../../core/utils/constants/shared_preferences_constants.dart';
import '../../../core/utils/constants/svg_constants.dart';
import '../../../core/widgets/container_button.dart';
import '../../../core/widgets/custom_button.dart';
import '../../../core/widgets/read_more_less/read_more_less.dart';
import '../../../core/widgets/shimmer_effect_build.dart';
import '../../../core/widgets/tab_bar_widget.dart';
import '../../controllers/general/general_controller.dart';
import '../../controllers/theme_controller.dart';
import '../quran_page/quran.dart';
import '../quran_page/widgets/search/search_extensions/highlight_extension.dart';
import 'controller/chapters_controller.dart';
import 'data/data_sources/books_bookmark_database.dart';

part 'controller/books_bookmarks_controller.dart';
part 'controller/books_controller.dart';
part 'controller/books_state.dart';
part 'controller/extensions/books_getters.dart';
part 'controller/extensions/books_storage_getters.dart';
part 'controller/extensions/books_ui.dart';
part 'data/models/book_info_model.dart';
part 'data/models/books_model.dart';
part 'data/models/chapter_model.dart';
part 'data/models/page_model.dart';
part 'data/models/part_model.dart';
part 'data/models/toc_model.dart';
part 'data/models/volume_model.dart';
part 'data/services/books_data_converter.dart';
part 'screens/books_bookmarks_screen.dart';
part 'screens/books_screen.dart';
part 'screens/chapters_screen.dart';
part 'screens/read_view_screen.dart';
part 'widgets/all_books_build.dart';
part 'widgets/book_cover_widget.dart';
part 'widgets/book_details_widget.dart';
part 'widgets/books_chapters_build.dart';
part 'widgets/books_last_read.dart';
part 'widgets/books_tab_bar_widget.dart';
part 'widgets/books_top_title_widget.dart';
part 'widgets/chapters_dropdown_widget.dart';
part 'widgets/search_build.dart';
part 'widgets/search_screen.dart';
part 'widgets/slider/bottom_slider.dart';
part 'widgets/slider/controller/slider_controller.dart';
part 'widgets/slider/top_slider.dart';
